FROM node:20-alpine as builder
WORKDIR /build

ARG VITE_API_URL=http://localhost:9000/api
ENV VITE_API_URL=$VITE_API_URL

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build


FROM nginx:alpine
WORKDIR /usr/share/nginx/html

COPY --from=builder /build/dist .

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
