FROM node:18-alpine as build
WORKDIR /build

COPY package*.json .
RUN npm install

COPY src ./src
COPY tsconfig.json .

RUN npm run build


FROM node:18-alpine as runtime
WORKDIR /app

COPY --from=build build/node_modules ./node_modules
COPY --from=build build/dist ./dist
COPY --from=build build/package*.json .

CMD [ "npm", "start" ]